[features]
seeds = false
[programs.localnet]
sol_escrow = "HKDuyYsjkZDwrYt7QtXrQNcw3QaDVsAKKFRRkm3RfoGg"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/rolandgavrilescu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
